name: React app deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Specify Node.js version
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the LTS version of Node.js
    
    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
